server:
  port: 8089
spring:
  devtools:
    restart:
      enabled: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://fengchao98.f3322.net:3306/iottyys?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
#    url: jdbc:mysql://10.113.255.138:3306/lmocp?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    hikari: # springboot 2.0 整合了hikari ,据说这是目前性能最好的java数据库连接池
    username: root
    password: zr6t0ES1bpvsCIYM
    initialization-mode: always
#  liquibase:
#    change-log: classpath:liquibase/master.xml
#    enabled: false
  jpa:
    hibernate:
      ddl-auto: update  # 第一次建表create  后面用update，要不然每次重启都会新建表
    show-sql: true
  redis:
    database: 0
    host: 192.168.31.245
    lettuce:
      pool:
        max-active: 8   #最大连接数据库连接数,设 -1 为没有限制
        max-idle: 8     #最大等待连接中的数量,设 0 为没有限制
        max-wait: -1ms  #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        min-idle: 0     #最小等待连接中的数量,设 0 为没有限制
      shutdown-timeout: 100ms
    password: ''
    port: 6379

