-- 条件
INSERT INTO lc_workplace_condition (id, `name`, measuring_unit_id, condition_type, `code`, remark, create_time,create_by, update_time, update_by, del_flag)
VALUES (1, '上宽(m)', null, 'RANGE', "sk", null, DATE (NOW()), null, null, null, 0),
       (2, '下宽(m)', null, 'RANGE',"xk", null, DATE (NOW()), null, null, null, 0),
       (3, '墙高(m)', null, 'RANGE',"qiangg", null, DATE (NOW()), null, null, null, 0),
       (4, '全高(m)', null, 'RANGE',"quang", null, DATE (NOW()), null, null, null, 0),
       (5, '面长(m)', null, 'RANGE',"mc", null, DATE (NOW()), null, null, null, 0),
       (6, '有效长度(m)', null, 'RANGE',"yxgd", null, DATE (NOW()), null, null, null, 0),
       (7, '采高(m)', null, 'RANGE',"cg", null, DATE (NOW()), null, null, null, 0),
       (8, '放煤厚度(m)', null, 'RANGE',"fmhd", null, DATE (NOW()), null, null, null, 0),
       (9, '硬度', null, 'REGULAR',"yd", null, DATE (NOW()), null, null, null, 0),
       (10, '比重', null, 'RANGE',"bz", null, DATE (NOW()), null, null, null, 0),
       (11, '循环方式', null, 'REGULAR',"xhfs", null, DATE (NOW()), null, null, null, 0),
       (12, '循环进度', null, 'RANGE',"xhjd", null, DATE (NOW()), null, null, null, 0),
       (13, '溜子(部)', null, 'RANGE',"lz", null, DATE (NOW()), null, null, null, 0),
       (14, '支架数量(个)', null, 'RANGE',"zjsl", null, DATE (NOW()), null, null, null, 0),
       (15, '架宽(m)', null, 'RANGE',"jk", null, DATE (NOW()), null, null, null, 0),
       (16, '采煤方式', null, 'REGULAR',"cmfs", null, DATE (NOW()), null, null, null, 0),
       (17, '机组型号', null, 'REGULAR',"jzxh", null, DATE (NOW()), null, null, null, 0),
       (18, '上下山', null, 'REGULAR',"sxs", null, DATE (NOW()), null, null, null, 0),
       (19, '岩别', null, 'REGULAR',"yb", null, DATE (NOW()), null, null, null, 0),
       (20, '排序(m)', null, 'RANGE',"px", null, DATE (NOW()), null, null, null, 0),
       (21, '巷别', null, 'REGULAR',"xb", null, DATE (NOW()), null, null, null, 0),
       (22, '断面(㎡)', null, 'RANGE',"dm", null, DATE (NOW()), null, null, null, 0),
       (23, '坡度(°)', null, 'RANGE',"pd", null, DATE (NOW()), null, null, null, 0),
       (24, '趴装名称', null, 'REGULAR',"pzmc", null, DATE (NOW()), null, null, null, 0);

-- 条件值
INSERT INTO lc_workplace_condition_value(id, `value`, `code`, condition_id, create_time, create_by, update_time,update_by, del_flag)
VALUES (1, "全煤", "yd-qm", 9, DATE (NOW()), null, null, null, 0),
       (2, "软岩", "yd-ry", 9, DATE (NOW()), null, null, null, 0),
       (3, "中硬", "yd-zy", 9, DATE (NOW()), null, null, null, 0),
       (4, "硬岩", "yd-yy", 9, DATE (NOW()), null, null, null, 0),
       (5, "特硬岩", "yd-tyy", 9, DATE (NOW()), null, null, null, 0),
       (6, "半煤岩", "yd-bmy", 9, DATE (NOW()), null, null, null, 0),
       (7, "多循环", "xhfs-dxh", 11, DATE (NOW()), null, null, null, 0),
       (8, "机割煤", "cmfs-jgm", 16, DATE (NOW()), null, null, null, 0),
       (9, "MG500", "jzxh-MG500", 17, DATE (NOW()), null, null, null, 0),
       (10, "1255-WD", "jzxh-1255-WD", 17, DATE (NOW()), null, null, null, 0),
       (11, "平巷", "sxs-px", 18, DATE (NOW()), null, null, null, 0),
       (12, "上山", "sxs-ss", 18, DATE (NOW()), null, null, null, 0),
       (13, "下山", "sxs-xs", 18, DATE (NOW()), null, null, null, 0),
       (14, "煤", "yb-m", 19, DATE (NOW()), null, null, null, 0),
       (15, "岩", "yb-y", 19, DATE (NOW()), null, null, null, 0),
       (16, "平", "xb-p", 21, DATE (NOW()), null, null, null, 0),
       (17, "上", "xb-s", 21, DATE (NOW()), null, null, null, 0),
       (18, "下", "xb-x", 21, DATE (NOW()), null, null, null, 0),
       (19, "机械", "pzmc-jx", 24, DATE (NOW()), null, null, null, 0),
       (20, "人力", "pzmc-rl", 24, DATE (NOW()), null, null, null, 0);
