nacos:
  config:
    bootstrap:
      log-enable: true # 支持日志级别的加载时机（如果需要集成dubbo，请使用此配置加载时机）
      enable: true # 设置参数nacos.config.bootstrap.enable=true，开启配置预加载功能
    max-retry: 10 # 主配置 最大重试次数
    auto-refresh: false # 主配置 是否开启自动刷新 (false:不监听属性变化,true:监听属性变化,但是对应的属性注解上也必须设置autoRefreshed = true才可以实时更新)
    config-retry-time: 3000 # 主配置 重试时间
    config-long-poll-timeout: 30000 # 主配置 配置监听长轮询超时时间
    enable-remote-sync-config: false # 主配置 开启注册监听器预加载配置服务（除非特殊业务需求，否则不推荐打开该参数）
    #允许nacos上的配置优先于本地配置; 意思是：如果nacos配置了某属性，然后在本地的application.yml配置了相同属性；那么会以nacos配置的优先;否则是本地的优先
    remote-first: true
    # 主配置 data-ids  (可以配置多个,如果多个配置文件中有相同的 属性 则优先取最前面的值)
    data-ids: application-static.yaml
    group: DEFAULT_GROUP # 主配置 group-id
    type: yaml # 主配置 配置文件类型
    server-addr: fengchao98.f3322.net:8848
    namespace: # 命名空间
